name: Check PR

on:
  pull_request:
    branches:
      - main
      - "release/**"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

permissions:
  contents: read
  pull-requests: write
  id-token: write
  actions: read
  statuses: write

concurrency:
  group: pr-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  skip-draft:
    name: Skip Draft PR
    if: ${{ github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip draft PR
        run: echo "Skipping checks for draft PR #${{ github.event.pull_request.number }}"

  pr-title:
    name: Check PR Title
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          disallowScopes: |
            release
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  test-and-build:
    name: Test and Build
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run build

      - name: Lint check (if available)
        run: |
          if pnpm run lint --help &>/dev/null; then
            echo "Running lint check..."
            pnpm run lint
          else
            echo "No lint script found, skipping..."
          fi

  release-branch-validation:
    name: Release Branch Validation
    if: ${{ !github.event.pull_request.draft && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate release branch format
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Valid release branch format: $BRANCH_NAME"
          else
            echo "❌ Invalid release branch format: $BRANCH_NAME"
            echo "Expected format: release/X.Y.Z (e.g., release/1.2.3)"
            exit 1
          fi

      - name: Check PR is targeting main
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" != "main" ]; then
            echo "❌ Release branch PRs must target 'main' branch"
            echo "Current target: ${{ github.event.pull_request.base.ref }}"
            exit 1
          fi
          echo "✅ PR correctly targets main branch"

      - name: Validate PR labels
        run: |
          LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          if [[ "$LABELS" == *"hotfix"* ]] || [[ "$LABELS" == *"automated"* ]]; then
            echo "✅ PR has appropriate labels: $LABELS"
          else
            echo "⚠️ Consider adding 'hotfix' or 'automated' labels to this release PR"
          fi

  security-check:
    name: Security Check
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: |
          echo "Running security audit..."
          pnpm audit --audit-level moderate || {
            echo "⚠️ Security vulnerabilities found. Please review and fix."
            echo "Run 'pnpm audit --fix' to automatically fix issues where possible."
            exit 1
          }
          echo "✅ No security vulnerabilities found"
