name: "Security & Dependencies"

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: pnpm install

      - name: Audit npm dependencies
        run: pnpm audit

      - name: Audit Rust dependencies
        run: |
          cargo install cargo-audit
          cd src-tauri && cargo audit

      - name: Check for outdated dependencies
        run: |
          echo "=== NPM Dependencies ===" 
          pnpm outdated || true
          echo "=== Rust Dependencies ==="
          cd src-tauri && cargo outdated || cargo install cargo-outdated && cargo outdated

  dependency-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Update dependencies
        run: |
          # Update npm dependencies
          pnpm update

          # Update Rust dependencies
          cd src-tauri
          cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated dependency updates"
          body: |
            This PR contains automated dependency updates.

            ## Changes
            - Updated npm dependencies to latest compatible versions
            - Updated Rust dependencies to latest compatible versions

            ## Testing
            Please test the application thoroughly before merging:
            - [ ] App builds successfully on all platforms
            - [ ] Core functionality works as expected
            - [ ] No new security vulnerabilities introduced

            ## Auto-generated
            This PR was created automatically by the dependency update workflow.
          branch: "automated/dependency-updates"
          delete-branch: true
